twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']

    paths:
        # pointe vers votre dossier d'images
        '%kernel.project_dir%/assets/images': images

when@test:
    twig:
        strict_variables: true
